version: "3.0"

services:
# бд, используемая для работы с пользователями и их правами
  postgres_privelege:
    image: postgres:16.3
    restart: always
    container_name: postgres_privelege
    env_file: .env
    environment:
      - POSTGRES_USER=${P_POSTGRES_USER}
      - POSTGRES_PASSWORD=${P_POSTGRES_PASSWORD}
      - POSTGRES_DB=${P_POSTGRES_DATABASE}
    volumes:
      - ./services/postgres/privelege/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      # - ./services/postgres/privelege/data:/var/lib/postgresql/data
    ports:
      - ${P_POSTGRES_PORT}:5432
    networks:
      - ecosystem
# бд, используемая для хранения архивов каких-либо записей
  postgres_archive:
    image: postgres:16.3
    restart: always
    container_name: postgres_archive
    environment:
      - POSTGRES_USER=${A_POSTGRES_USER}
      - POSTGRES_PASSWORD=${A_POSTGRES_PASSWORD}
      - POSTGRES_DB=${A_POSTGRES_DATABASE}
    volumes:
      - ./services/postgres/archive/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      # - ./services/postgres/archive/data:/var/lib/postgresql/data
    ports:
      - ${A_POSTGRES_PORT}:5432
    networks:
      - ecosystem
  # pgamdin:
  #   image: dpage/pgadmin4:latest
  #   restart: always
  #   container_name: pgamdin
  #   env_file: .env
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  #   ports:
  #     - 82:80
  #   networks:
  #     - ecosystem

networks:
  ecosystem:
    driver: bridge